# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"

before_install:
    -export DJANGO_SETTINGS_MODULE=tests.settings

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: py.test

# report coverage to coveralls.io
after_success: coveralls
